# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b6137088c80d0dcd8933a7eee9d3aa74c22ea5c31ff44169b1d918b2ac1bdc9743abeeb68471bba7bc5887aae91a90898594d1e405df752ebfc8e914d5c681

test:
  secret_key_base: 369d1dbd2c6ef4d21c0373eb120a29332a11b15442405c362c74c200db73d1a323c6b3827f08e1bff6f834756137c73ed65f21cf015bca4027946422b169966e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
